version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-capstone-db
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2580"
      POSTGRES_DB: support_desk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
